### ISSUE TITLE
stops at 3.24.0

### ISSUE THREAD

**Issue by mmaiers-nmdp** [ANHIG/HLA-WMDA#24]
The files stop at 3.24.0.  Where are 3.25.0, etc.
OK.  I see that this has moved but what about the various versions?
https://github.com/ANHIG/IMGTHLA/tree/Latest/wmda has 3.28 but where is 3.27?

**Comment by ANHIG** [comment]
As stated in the README file;

"As of release 3.25.0, this repository will be included within the main IPD-IMGT/HLA Repository located at https://github.com/ANHIG/IMGTHLA, the data is located in the wmda subdirectory. This repository will not be updated with subsequent releases.”

**Comment by ANHIG** [comment]
As stated in the README file;

"As of release 3.25.0, this repository will be included within the main IPD-IMGT/HLA Repository located at https://github.com/ANHIG/IMGTHLA, the data is located in the wmda subdirectory. This repository will not be updated with subsequent releases.”

Regards

Jame Robinson

**Comment by mmaiers-nmdp** [comment]
OK, that answers my first question.

I think I answered my 2nd question 'where is 3.27'?
I will post it here so others can read about it.

The different versions of the WMDA files are in different **branches** of the IMGTHLA repo.

Two new questions:
1. Why represent the delimited version string "3.26.0" with an un-delimited "3260" nomenclature?
The latter requires custom parsing.

2. Could this be made more consistent?  How about one archive with all versions that is added to quarterly?  Checksums on every version?

branches:
300 - 3210 do no exist (although they are in the menu)
3220 has no checksum
3230 has no checksum
3240 has checksum and all versions 300 - 3240
3250 has checksum and all versions 300 - 3250
3260 has no checksum
3270 has checksum
3280 has checksum
